// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf C++ Version: 5.29.3

#include "message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Messages {
              template <typename>
PROTOBUF_CONSTEXPR KeepAliveRequest::KeepAliveRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct KeepAliveRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KeepAliveRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeepAliveRequestDefaultTypeInternal() {}
  union {
    KeepAliveRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeepAliveRequestDefaultTypeInternal _KeepAliveRequest_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR KeepAliveNoti::KeepAliveNoti(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct KeepAliveNotiDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KeepAliveNotiDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~KeepAliveNotiDefaultTypeInternal() {}
  union {
    KeepAliveNoti _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KeepAliveNotiDefaultTypeInternal _KeepAliveNoti_default_instance_;

inline constexpr ConnectedResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : index_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConnectedResponse::ConnectedResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ConnectedResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConnectedResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConnectedResponseDefaultTypeInternal() {}
  union {
    ConnectedResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConnectedResponseDefaultTypeInternal _ConnectedResponse_default_instance_;

inline constexpr MessageWrapper::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_size_{0},
        payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR MessageWrapper::MessageWrapper(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MessageWrapperDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageWrapperDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageWrapperDefaultTypeInternal() {}
  union {
    MessageWrapper _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageWrapperDefaultTypeInternal _MessageWrapper_default_instance_;
}  // namespace Messages
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_message_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_message_2eproto = nullptr;
const ::uint32_t
    TableStruct_message_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Messages::MessageWrapper, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::Messages::MessageWrapper, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Messages::MessageWrapper, _impl_.message_size_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::Messages::MessageWrapper, _impl_.payload_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Messages::ConnectedResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Messages::ConnectedResponse, _impl_.index_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Messages::KeepAliveNoti, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Messages::KeepAliveRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Messages::MessageWrapper)},
        {13, -1, -1, sizeof(::Messages::ConnectedResponse)},
        {22, -1, -1, sizeof(::Messages::KeepAliveNoti)},
        {30, -1, -1, sizeof(::Messages::KeepAliveRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Messages::_MessageWrapper_default_instance_._instance,
    &::Messages::_ConnectedResponse_default_instance_._instance,
    &::Messages::_KeepAliveNoti_default_instance_._instance,
    &::Messages::_KeepAliveRequest_default_instance_._instance,
};
const char descriptor_table_protodef_message_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rmessage.proto\022\010Messages\"\332\001\n\016MessageWra"
    "pper\022\024\n\014message_size\030\001 \001(\005\0229\n\022connected_"
    "response\030\n \001(\0132\033.Messages.ConnectedRespo"
    "nseH\000\0222\n\017keep_alive_noti\030\013 \001(\0132\027.Message"
    "s.KeepAliveNotiH\000\0228\n\022keep_alive_request\030"
    "\014 \001(\0132\032.Messages.KeepAliveRequestH\000B\t\n\007p"
    "ayload\"\"\n\021ConnectedResponse\022\r\n\005index\030\001 \001"
    "(\005\"\017\n\rKeepAliveNoti\"\022\n\020KeepAliveRequestb"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_message_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_message_2eproto = {
    false,
    false,
    327,
    descriptor_table_protodef_message_2eproto,
    "message.proto",
    &descriptor_table_message_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_message_2eproto::offsets,
    file_level_enum_descriptors_message_2eproto,
    file_level_service_descriptors_message_2eproto,
};
namespace Messages {
// ===================================================================

class MessageWrapper::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Messages::MessageWrapper, _impl_._oneof_case_);
};

void MessageWrapper::set_allocated_connected_response(::Messages::ConnectedResponse* connected_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (connected_response) {
    ::google::protobuf::Arena* submessage_arena = connected_response->GetArena();
    if (message_arena != submessage_arena) {
      connected_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, connected_response, submessage_arena);
    }
    set_has_connected_response();
    _impl_.payload_.connected_response_ = connected_response;
  }
  // @@protoc_insertion_point(field_set_allocated:Messages.MessageWrapper.connected_response)
}
void MessageWrapper::set_allocated_keep_alive_noti(::Messages::KeepAliveNoti* keep_alive_noti) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (keep_alive_noti) {
    ::google::protobuf::Arena* submessage_arena = keep_alive_noti->GetArena();
    if (message_arena != submessage_arena) {
      keep_alive_noti = ::google::protobuf::internal::GetOwnedMessage(message_arena, keep_alive_noti, submessage_arena);
    }
    set_has_keep_alive_noti();
    _impl_.payload_.keep_alive_noti_ = keep_alive_noti;
  }
  // @@protoc_insertion_point(field_set_allocated:Messages.MessageWrapper.keep_alive_noti)
}
void MessageWrapper::set_allocated_keep_alive_request(::Messages::KeepAliveRequest* keep_alive_request) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (keep_alive_request) {
    ::google::protobuf::Arena* submessage_arena = keep_alive_request->GetArena();
    if (message_arena != submessage_arena) {
      keep_alive_request = ::google::protobuf::internal::GetOwnedMessage(message_arena, keep_alive_request, submessage_arena);
    }
    set_has_keep_alive_request();
    _impl_.payload_.keep_alive_request_ = keep_alive_request;
  }
  // @@protoc_insertion_point(field_set_allocated:Messages.MessageWrapper.keep_alive_request)
}
MessageWrapper::MessageWrapper(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Messages.MessageWrapper)
}
inline PROTOBUF_NDEBUG_INLINE MessageWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Messages::MessageWrapper& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

MessageWrapper::MessageWrapper(
    ::google::protobuf::Arena* arena,
    const MessageWrapper& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MessageWrapper* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.message_size_ = from._impl_.message_size_;
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kConnectedResponse:
        _impl_.payload_.connected_response_ = ::google::protobuf::Message::CopyConstruct<::Messages::ConnectedResponse>(arena, *from._impl_.payload_.connected_response_);
        break;
      case kKeepAliveNoti:
        _impl_.payload_.keep_alive_noti_ = ::google::protobuf::Message::CopyConstruct<::Messages::KeepAliveNoti>(arena, *from._impl_.payload_.keep_alive_noti_);
        break;
      case kKeepAliveRequest:
        _impl_.payload_.keep_alive_request_ = ::google::protobuf::Message::CopyConstruct<::Messages::KeepAliveRequest>(arena, *from._impl_.payload_.keep_alive_request_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Messages.MessageWrapper)
}
inline PROTOBUF_NDEBUG_INLINE MessageWrapper::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void MessageWrapper::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.message_size_ = {};
}
MessageWrapper::~MessageWrapper() {
  // @@protoc_insertion_point(destructor:Messages.MessageWrapper)
  SharedDtor(*this);
}
inline void MessageWrapper::SharedDtor(MessageLite& self) {
  MessageWrapper& this_ = static_cast<MessageWrapper&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void MessageWrapper::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:Messages.MessageWrapper)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kConnectedResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.connected_response_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.connected_response_);
      }
      break;
    }
    case kKeepAliveNoti: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.keep_alive_noti_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.keep_alive_noti_);
      }
      break;
    }
    case kKeepAliveRequest: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.keep_alive_request_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.keep_alive_request_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* MessageWrapper::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MessageWrapper(arena);
}
constexpr auto MessageWrapper::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MessageWrapper),
                                            alignof(MessageWrapper));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MessageWrapper::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MessageWrapper_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MessageWrapper::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MessageWrapper>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MessageWrapper::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MessageWrapper>(), &MessageWrapper::ByteSizeLong,
            &MessageWrapper::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MessageWrapper, _impl_._cached_size_),
        false,
    },
    &MessageWrapper::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MessageWrapper::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 4, 3, 0, 2> MessageWrapper::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    12, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294963710,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Messages::MessageWrapper>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 message_size = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessageWrapper, _impl_.message_size_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MessageWrapper, _impl_.message_size_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 message_size = 1;
    {PROTOBUF_FIELD_OFFSET(MessageWrapper, _impl_.message_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .Messages.ConnectedResponse connected_response = 10;
    {PROTOBUF_FIELD_OFFSET(MessageWrapper, _impl_.payload_.connected_response_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Messages.KeepAliveNoti keep_alive_noti = 11;
    {PROTOBUF_FIELD_OFFSET(MessageWrapper, _impl_.payload_.keep_alive_noti_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Messages.KeepAliveRequest keep_alive_request = 12;
    {PROTOBUF_FIELD_OFFSET(MessageWrapper, _impl_.payload_.keep_alive_request_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Messages::ConnectedResponse>()},
    {::_pbi::TcParser::GetTable<::Messages::KeepAliveNoti>()},
    {::_pbi::TcParser::GetTable<::Messages::KeepAliveRequest>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void MessageWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:Messages.MessageWrapper)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_size_ = 0;
  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MessageWrapper::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MessageWrapper& this_ = static_cast<const MessageWrapper&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MessageWrapper::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MessageWrapper& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Messages.MessageWrapper)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 message_size = 1;
          if (this_._internal_message_size() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_message_size(), target);
          }

          switch (this_.payload_case()) {
            case kConnectedResponse: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  10, *this_._impl_.payload_.connected_response_, this_._impl_.payload_.connected_response_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kKeepAliveNoti: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  11, *this_._impl_.payload_.keep_alive_noti_, this_._impl_.payload_.keep_alive_noti_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kKeepAliveRequest: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  12, *this_._impl_.payload_.keep_alive_request_, this_._impl_.payload_.keep_alive_request_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Messages.MessageWrapper)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MessageWrapper::ByteSizeLong(const MessageLite& base) {
          const MessageWrapper& this_ = static_cast<const MessageWrapper&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MessageWrapper::ByteSizeLong() const {
          const MessageWrapper& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Messages.MessageWrapper)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 message_size = 1;
            if (this_._internal_message_size() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_message_size());
            }
          }
          switch (this_.payload_case()) {
            // .Messages.ConnectedResponse connected_response = 10;
            case kConnectedResponse: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.connected_response_);
              break;
            }
            // .Messages.KeepAliveNoti keep_alive_noti = 11;
            case kKeepAliveNoti: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.keep_alive_noti_);
              break;
            }
            // .Messages.KeepAliveRequest keep_alive_request = 12;
            case kKeepAliveRequest: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.keep_alive_request_);
              break;
            }
            case PAYLOAD_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MessageWrapper::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MessageWrapper*>(&to_msg);
  auto& from = static_cast<const MessageWrapper&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Messages.MessageWrapper)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_message_size() != 0) {
    _this->_impl_.message_size_ = from._impl_.message_size_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kConnectedResponse: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.connected_response_ =
              ::google::protobuf::Message::CopyConstruct<::Messages::ConnectedResponse>(arena, *from._impl_.payload_.connected_response_);
        } else {
          _this->_impl_.payload_.connected_response_->MergeFrom(from._internal_connected_response());
        }
        break;
      }
      case kKeepAliveNoti: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.keep_alive_noti_ =
              ::google::protobuf::Message::CopyConstruct<::Messages::KeepAliveNoti>(arena, *from._impl_.payload_.keep_alive_noti_);
        } else {
          _this->_impl_.payload_.keep_alive_noti_->MergeFrom(from._internal_keep_alive_noti());
        }
        break;
      }
      case kKeepAliveRequest: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.keep_alive_request_ =
              ::google::protobuf::Message::CopyConstruct<::Messages::KeepAliveRequest>(arena, *from._impl_.payload_.keep_alive_request_);
        } else {
          _this->_impl_.payload_.keep_alive_request_->MergeFrom(from._internal_keep_alive_request());
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageWrapper::CopyFrom(const MessageWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Messages.MessageWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MessageWrapper::InternalSwap(MessageWrapper* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.message_size_, other->_impl_.message_size_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata MessageWrapper::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ConnectedResponse::_Internal {
 public:
};

ConnectedResponse::ConnectedResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Messages.ConnectedResponse)
}
ConnectedResponse::ConnectedResponse(
    ::google::protobuf::Arena* arena, const ConnectedResponse& from)
    : ConnectedResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ConnectedResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ConnectedResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.index_ = {};
}
ConnectedResponse::~ConnectedResponse() {
  // @@protoc_insertion_point(destructor:Messages.ConnectedResponse)
  SharedDtor(*this);
}
inline void ConnectedResponse::SharedDtor(MessageLite& self) {
  ConnectedResponse& this_ = static_cast<ConnectedResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ConnectedResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ConnectedResponse(arena);
}
constexpr auto ConnectedResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ConnectedResponse),
                                            alignof(ConnectedResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ConnectedResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ConnectedResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ConnectedResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ConnectedResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ConnectedResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ConnectedResponse>(), &ConnectedResponse::ByteSizeLong,
            &ConnectedResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ConnectedResponse, _impl_._cached_size_),
        false,
    },
    &ConnectedResponse::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ConnectedResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ConnectedResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Messages::ConnectedResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 index = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ConnectedResponse, _impl_.index_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ConnectedResponse, _impl_.index_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 index = 1;
    {PROTOBUF_FIELD_OFFSET(ConnectedResponse, _impl_.index_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ConnectedResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Messages.ConnectedResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.index_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ConnectedResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ConnectedResponse& this_ = static_cast<const ConnectedResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ConnectedResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ConnectedResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Messages.ConnectedResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 index = 1;
          if (this_._internal_index() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_index(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Messages.ConnectedResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ConnectedResponse::ByteSizeLong(const MessageLite& base) {
          const ConnectedResponse& this_ = static_cast<const ConnectedResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ConnectedResponse::ByteSizeLong() const {
          const ConnectedResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Messages.ConnectedResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 index = 1;
            if (this_._internal_index() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_index());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ConnectedResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ConnectedResponse*>(&to_msg);
  auto& from = static_cast<const ConnectedResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Messages.ConnectedResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_index() != 0) {
    _this->_impl_.index_ = from._impl_.index_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConnectedResponse::CopyFrom(const ConnectedResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Messages.ConnectedResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ConnectedResponse::InternalSwap(ConnectedResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.index_, other->_impl_.index_);
}

::google::protobuf::Metadata ConnectedResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class KeepAliveNoti::_Internal {
 public:
};

KeepAliveNoti::KeepAliveNoti(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Messages.KeepAliveNoti)
}
KeepAliveNoti::KeepAliveNoti(
    ::google::protobuf::Arena* arena,
    const KeepAliveNoti& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  KeepAliveNoti* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Messages.KeepAliveNoti)
}

inline void* KeepAliveNoti::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) KeepAliveNoti(arena);
}
constexpr auto KeepAliveNoti::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(KeepAliveNoti),
                                            alignof(KeepAliveNoti));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull KeepAliveNoti::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_KeepAliveNoti_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &KeepAliveNoti::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<KeepAliveNoti>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &KeepAliveNoti::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<KeepAliveNoti>(), &KeepAliveNoti::ByteSizeLong,
            &KeepAliveNoti::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(KeepAliveNoti, _impl_._cached_size_),
        false,
    },
    &KeepAliveNoti::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* KeepAliveNoti::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> KeepAliveNoti::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Messages::KeepAliveNoti>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata KeepAliveNoti::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class KeepAliveRequest::_Internal {
 public:
};

KeepAliveRequest::KeepAliveRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Messages.KeepAliveRequest)
}
KeepAliveRequest::KeepAliveRequest(
    ::google::protobuf::Arena* arena,
    const KeepAliveRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  KeepAliveRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Messages.KeepAliveRequest)
}

inline void* KeepAliveRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) KeepAliveRequest(arena);
}
constexpr auto KeepAliveRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(KeepAliveRequest),
                                            alignof(KeepAliveRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull KeepAliveRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_KeepAliveRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &KeepAliveRequest::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<KeepAliveRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &KeepAliveRequest::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<KeepAliveRequest>(), &KeepAliveRequest::ByteSizeLong,
            &KeepAliveRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(KeepAliveRequest, _impl_._cached_size_),
        false,
    },
    &KeepAliveRequest::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* KeepAliveRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> KeepAliveRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Messages::KeepAliveRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata KeepAliveRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Messages
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_message_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
